---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/calculate":
    post:
      summary: calculate
      tags:
      - Calculate Score
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                example_0:
                  value:
                    auto: econômico
                    disability: inelegivel
                    home: econômico
                    life: padrão
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                age:
                  type: integer
                  example: 35
                dependents:
                  type: integer
                  example: 2
                house:
                  type: object
                  properties:
                    ownership_status:
                      type: string
                      example: owned
                      enum:
                      - owned
                      - rented
                  required:
                  - ownership_status
                income:
                  type: integer
                  example: 0
                marital_status:
                  type: string
                  example: married
                  enum:
                  - single
                  - married
                risk_questions:
                  type: array
                  items:
                    type: integer
                  example:
                  - 0
                  - 1
                  - 0
                vehicle:
                  type: object
                  properties:
                    year:
                      type: integer
                      example: 2018
              required:
              - age
              - dependents
              - house
              - income
              - marital_status
              - risk_questions
              - vehicle
servers:
- url: http://localhost:3000
  description: Local server
